### ISSUE TITLE
source code of version 1.8.5 ?

### ISSUE THREAD

**Issue by xylo** [TakehideSoh/Scarab#4]
I downloaded Scarab 1.8.5 from http://kix.istc.kobe-u.ac.jp/~soh/scarab/index.html and wanted to add some features.  However, the sources here look to be for version 1.6.9.  Is there any chance the git repository gets updated?

**Comment by TakehideSoh** [comment]
I uploaded the latest sources to both the web and git repository.

**Comment by xylo** [comment]
Thank you. :+1:
